config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :update, :index]
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:destroy]
  resources :friend_requests, only: [:create, :destroy] do
    post "/accept", to: "friend_requests#accept", on: :member
    post "/generate", to: "friend_requests#generate", on: :collection
  end
  root 'posts#index'
  patch "/update_avatar/:id", to: "users#update_avatar", as: "update_avatar"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: :user_id
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true

  after_create_commit { broadcast_update_to "comments", partial: "comments/for_commentable", target: "comments#{post.id}", locals: {commentable: post}}
  after_destroy_commit { broadcast_update_to "comments", partial: "comments/for_commentable", target: "comments#{post.id}", locals: {commentable: post}}

  def post(comment = self)
    commentable = comment.commentable
    return commentable if commentable.is_a?(Post)
    post(commentable)
  end

  def all_replies(all = [])
    return all unless comments.any?

    all << comments
    comments.each do |c|
      return c.all_replies(all)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if comment_params[:post_id]
      comment = Post.find(comment_params[:post_id]).comments.build(body: comment_params[:body])
    elsif comment_params[:comment_id]
      comment = Comment.find(comment_params[:comment_id]).comments.build(body: comment_params[:body])
    end
    comment.author = current_user
    comment.save
  end

  def destroy
    Comment.find(params[:id]).destroy
  end

  private

  def comment_params
    params.require(:comment).permit([:body, :post_id, :comment_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
- author = comment.author
%div{data:{controller: "visibility"}}
  .text-sm.grid.grid-rows-auto.w-full.rounded-3xl.border.px-3.py-2.gap-1{id: "comment#{comment.id}"}
    .inline-flex.gap-1
      = link_to author, class: "inline-flex min-w-max items-start gap-1 hover:underline" do
        = image_tag url_for(author.avatar_thumbnail("24")), class: "rounded-md"
        #{author.first_name}:
      .break-all.flex-grow
        = comment.body
      .inline-flex.gap-2
        .text-blue-400.cursor-pointer.self-center.hover:text-blue-500{data:{action: "click->visibility#toggle"}}
          Reply
        = link_to comment_path(comment), method: :delete, class: "self-center", data: {controller: "reveal-for", "reveal-for-id-value": comment.author.id} do
          = heroicon "trash", options: {class: "h-4 text-gray-600 hover:text-red-600"}
  .hidden{data: {visibility_target: "toggle"}}
    = render "comments/form", commentable: comment
- if comment.comments.any?
  .flex.w-full.border-l-2.border-gray-300
    .flex-grow.ml-3
      = render "comments/for_commentable", commentable: comment

app/views/comments/_for_commentable.html.haml
.grid.grid-rows-auto.gap-2{id: "comments#{commentable.id}"}
  - commentable.comments.each do |c|
    = futurize "comments/comment", comment: c, extends: :div

app/views/comments/_form.html.haml
- is_post = commentable.is_a?(Post)
= form_with url: comments_path, scope: :comment, method: :post, data: {controller: "input", action: "turbo:submit-end->input#clear"} do |f|
  .inline-flex.w-full.flex-col.gap-2
    = f.hidden_field (commentable.class.name.downcase + "_id").to_sym, value: commentable.id
    = f.text_area :body,
    class: "border rounded px-3 col-start-2 h-10 w-1/2 mx-auto text-sm",
    placeholder: "#{is_post ? " Add comment..." : "Reply..."}",
    data: {input_target: "input"}
    = f.submit "#{is_post ? "Comment" : "Reply"}", class: "w-max px-1 mx-auto rounded text-white bg-blue-400 hover:bg-blue-500 cursor-pointer"