config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :update, :index]
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:destroy]
  resources :friend_requests, only: [:create, :destroy] do
    post "/accept", to: "friend_requests#accept", on: :member
    post "/generate", to: "friend_requests#generate", on: :collection
  end
  root 'posts#index'
  patch "/update_avatar/:id", to: "users#update_avatar", as: "update_avatar"
end

app/models/user.rb
require 'down'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  has_many :posts, inverse_of: 'author', dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :friend_requests, dependent: :destroy
  has_many :received_friend_requests, class_name: 'FriendRequest', foreign_key: :recipient_id, dependent: :destroy
  has_many :sent_friend_requests, class_name: 'FriendRequest', foreign_key: :sender_id, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friendships_as_user_a, class_name: 'Friendship', foreign_key: :user_a_id
  has_many :friends_from_a, through: :friendships_as_user_a, class_name: 'User', source: :friend_b
  has_many :friendships_as_user_b, class_name: 'Friendship', foreign_key: :user_b_id
  has_many :friends_from_b, through: :friendships_as_user_b, class_name: 'User', source: :friend_a

  has_one_attached :avatar, dependent: :destroy

  validates :avatar, blob: { content_type: :image }
  validates :email, uniqueness: true, presence: true

  before_create :set_avatar

  after_create do
    UserMailer.with(user: self).welcome.deliver_now
    generate_friend_request(5)
  end

  after_update {broadcast_update_to "user_bio", partial: "users/bio", target: "bio#{id}", locals: {user: self}}

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split(" ")[0]
      user.last_name = auth.info.name.split(" ")[1..-1].join(" ")
      user.avatar.attach(io: Down.download(auth.info.image), filename: "avatar.jpg")
    end
  end

  def generate_friend_request(amount = 1)
    strangers.sample(amount).each do |stranger|
      stranger.sent_friend_requests.build(recipient: self).save
    end
  end

  def friends_with?(user)
    friends.include?(user)
  end

  def friendships
    friendships_as_user_a + friendships_as_user_b
  end

  def friends
    friends_from_a + friends_from_b
  end

  def has_liked?(post)
    liked_posts.include?(post)
  end

  def friendship_with(user)
    Friendship.find_by("user_a_id = ? OR user_b_id = ?", user.id, user.id)
  end

  def strangers
    (User.all - friends - [self])
  end

  def notifications
    received_friend_requests.order(created_at: :desc)
  end
  
  def request_to(user)
    sent_friend_requests.find_by(recipient: user)
  end
  
  def request_from(user)
    received_friend_requests.find_by(sender: user)
  end

  def request_with(user)
    FriendRequest.find_by(recipient: self, sender: user) || FriendRequest.find_by(recipient: user, sender: self)
  end

  def request_recipients
    sent_friend_requests.pluck(:recipient_id)
    end

  def request_senders
    received_friend_requests.pluck(:sender_id)
  end

  def avatar_thumbnail(size = "32")
    avatar.variant(:gravity=>"Center", resize: "#{size}x#{size}^", crop: "#{size}x#{size}+0+0").processed
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def set_avatar(url = "https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y")
    if !avatar.attached?
      image = Down.download(url)
      avatar.attach(io: image, filename: "avatar.jpg")
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.where.not(id: current_user.id).order(:first_name)
  end

  def update_avatar
    user = User.find(params[:id])
    user.update(avatar: params[:avatar])
  end

  def update
    User.find(params[:id]).update!(bio: params[:user][:bio])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bio.html.haml
- if user.bio.blank?
  .text-gray-400.mt-2
    No bio
- else
  = user.bio

app/views/users/_friend_request.html.haml
.hover:bg-gray-200{id: dom_id(fr)}
  = link_to fr.sender do
    .inline-flex.gap-3.p-2.w-full
      = image_tag url_for(fr.sender.avatar_thumbnail("48")), class: "rounded"
      %div
        .text-md.flex-grow
          #{fr.sender.first_name} wants to be friends
        .inline-flex.mx-auto
          = link_to "Accept", accept_friend_request_path(fr, user: fr.recipient), method: :post,
                    class: "bg-blue-400 text-white px-2 rounded hover:bg-blue-500 mx-3"
          = link_to "Decline", friend_request_path(fr), method: :delete,
                    class: "bg-gray-300 text-white px-2 rounded hover:bg-gray-400"

app/views/users/_friends.html.haml
.mx-3{id: "friends#{user.id}"}
  - user.friends.each do |friend|
    = render "users/user", user: friend

app/views/users/_notifications.html.haml
= turbo_stream_from "bell"
= turbo_stream_from "notifications"
#notifs
  %dib{id: "bell#{recipient.id}"}
    = render "users/buttons/bell", enable: enable
  .hidden{id: "notifs-box#{recipient.id}"}
    = render "users/notifs_box", recipient: recipient

app/views/users/_notifs_box.html.haml
.absolute.right-16.top-14.w-max
  .bg-white.border.max-h-96.overflow-y-auto
    - if recipient.notifications.any?
      #notifications.grid.grid-rows-auto.gap-2.p-2
        - recipient.notifications.each do |notif|
          - if notif.class == FriendRequest
            = render "users/friend_request", fr: notif
    - else
      .w-80.py-10.text-center.text-gray-400
        No notifications
  .bg-blue-200
    = link_to "Generate Friend Request", generate_friend_requests_path, method: :post

app/views/users/_profile.html.haml
.relative.-top-14.-bottom-14
  .inline-flex.w-full.justify-center
    - if user == current_user
      = form_with url: update_avatar_path, method: :patch, data: {controller: "avatar"}, id: "avatar-form" do |f|
        = f.file_field :avatar, hidden: true, data: {action: "change->avatar#Submit"}, accept: "image/png, image/gif, image/jpeg"
        = f.label :avatar, class: "pointer-events-none" do
          .group.cursor-pointer.rounded-full.pointer-events-auto
            #{image_tag url_for(user.avatar_thumbnail("96")), class: "rounded-full justify-self-center border-2 border-blue-300"}
            .text-transparent.group-hover:text-black.text-center.relative.bottom-14.h-0
              Change
    - else
      = image_tag url_for(user.avatar_thumbnail("96")), class: "rounded-full border-2 border-blue-300"
  .text-center.text-4xl.font-medium.text-gray-700.mt-5
    = user.full_name
  .text-center{class: "w-1/2 mx-auto", data:{controller: "visibility"}}
    .text-gray-700{data:{visibility_target: "toggle"}}
      = turbo_stream_from "user_bio"
      .break-all{id: "bio#{user.id}"}
        = render "users/bio", user: user
      - if user == current_user
        .text-sm.cursor-pointer.text-gray-500{data:{action: "click->visibility#toggle"}}
          Edit
    - if user == current_user
      = form_with model: user, class: "hidden", data:{controller: "input", visibility_target: "toggle"} do |f|
        = f.text_area :bio, class: "text-center w-full px-2", data:{input_target: "input"}
        %br
        = f.submit "Save", class: "bg-blue-400 text-white px-2 rounded cursor-pointer", data:{action: "click->visibility#toggle"}
  .text-center.mt-7
    - if user != current_user
      #friendship-button
        = render "users/buttons/add_remove_friend", user: user

app/views/users/_strangers.html.haml
.grid.grid-rows-auto.px-3.py-2.rounded.mt-48.border.shadow.bg-white.mx-auto{class: "w-1/2"}
  .text-4xl.font-medium.italic.text-blue-500.text-center.border-b.border-blue-200
    Find friends
  .grid.grid-rows-auto.mt-3
    - strangers.each do |stranger|
      %div
        = render "users/user", user: stranger
  .text-center.text-blue-400.italic.hover:text-blue-500
    = link_to "More...", users_path

app/views/users/_user.html.haml
= link_to user_path(user), id: dom_id(user)  do
  .inline-flex.items-center.gap-3.w-full.px-3.py-1.rounded.hover:bg-gray-200
    = image_tag(url_for(user.avatar_thumbnail("50")), class: "rounded-sm")
    .text-xl.flex-grow
      = user.full_name

app/views/users/index.html.haml
.text-4xl.text-center.italic.font-medium.text-blue-400.mt-20.mb-3
  All users:
.mx-auto.grid.grid-rows-auto.gap-2{class: "w-1/3"}
  - @users.each do |u|
    .border-b.px-2.py-1.grid.grid-rows-auto.bg-white.rounded-sm.shadow-sm
      = futurize "users/user", user: u, extends: :div do
        .text-center.py-2
          loading...
      .justify-self-end.my-2
        = futurize "users/buttons/add_remove_friend", user: u, extends: :div

app/views/users/show.html.haml
.bg-white.my-36.mx-auto.rounded.shadow-lg.border-2.border-blue-300{class: "w-1/2"}
  .bg-gray-50.border-b-2.border-gray-300
    = render "profile", user: @user
  .grid.grid-cols-3.mb-5
    .w-fit-content
      .text-2xl.font-medium.text-center.mt-10
        Friends
      = turbo_stream_from "friends"
      = futurize "users/friends", user: @user, extends: :div
    .col-span-2.mx-10
      %div{class: "w-2/3 mx-auto"}
        = render "posts/new" if @user == current_user
      .mb-5
        = turbo_stream_from "posts"
        = futurize "posts/posts", posts: @user.posts.order_desc, user: current_user, extends: :div