config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :update, :index]
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:destroy]
  resources :friend_requests, only: [:create, :destroy] do
    post "/accept", to: "friend_requests#accept", on: :member
    post "/generate", to: "friend_requests#generate", on: :collection
  end
  root 'posts#index'
  patch "/update_avatar/:id", to: "users#update_avatar", as: "update_avatar"
end

app/models/user.rb
require 'down'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  has_many :posts, inverse_of: 'author', dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :friend_requests, dependent: :destroy
  has_many :received_friend_requests, class_name: 'FriendRequest', foreign_key: :recipient_id, dependent: :destroy
  has_many :sent_friend_requests, class_name: 'FriendRequest', foreign_key: :sender_id, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friendships_as_user_a, class_name: 'Friendship', foreign_key: :user_a_id
  has_many :friends_from_a, through: :friendships_as_user_a, class_name: 'User', source: :friend_b
  has_many :friendships_as_user_b, class_name: 'Friendship', foreign_key: :user_b_id
  has_many :friends_from_b, through: :friendships_as_user_b, class_name: 'User', source: :friend_a

  has_one_attached :avatar, dependent: :destroy

  validates :avatar, blob: { content_type: :image }
  validates :email, uniqueness: true, presence: true

  before_create :set_avatar

  after_create do
    UserMailer.with(user: self).welcome.deliver_now
    generate_friend_request(5)
  end

  after_update {broadcast_update_to "user_bio", partial: "users/bio", target: "bio#{id}", locals: {user: self}}

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split(" ")[0]
      user.last_name = auth.info.name.split(" ")[1..-1].join(" ")
      user.avatar.attach(io: Down.download(auth.info.image), filename: "avatar.jpg")
    end
  end

  def generate_friend_request(amount = 1)
    strangers.sample(amount).each do |stranger|
      stranger.sent_friend_requests.build(recipient: self).save
    end
  end

  def friends_with?(user)
    friends.include?(user)
  end

  def friendships
    friendships_as_user_a + friendships_as_user_b
  end

  def friends
    friends_from_a + friends_from_b
  end

  def has_liked?(post)
    liked_posts.include?(post)
  end

  def friendship_with(user)
    Friendship.find_by("user_a_id = ? OR user_b_id = ?", user.id, user.id)
  end

  def strangers
    (User.all - friends - [self])
  end

  def notifications
    received_friend_requests.order(created_at: :desc)
  end
  
  def request_to(user)
    sent_friend_requests.find_by(recipient: user)
  end
  
  def request_from(user)
    received_friend_requests.find_by(sender: user)
  end

  def request_with(user)
    FriendRequest.find_by(recipient: self, sender: user) || FriendRequest.find_by(recipient: user, sender: self)
  end

  def request_recipients
    sent_friend_requests.pluck(:recipient_id)
    end

  def request_senders
    received_friend_requests.pluck(:sender_id)
  end

  def avatar_thumbnail(size = "32")
    avatar.variant(:gravity=>"Center", resize: "#{size}x#{size}^", crop: "#{size}x#{size}+0+0").processed
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def set_avatar(url = "https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y")
    if !avatar.attached?
      image = Down.download(url)
      avatar.attach(io: image, filename: "avatar.jpg")
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.where.not(id: current_user.id).order(:first_name)
  end

  def update_avatar
    user = User.find(params[:id])
    user.update(avatar: params[:avatar])
  end

  def update
    User.find(params[:id]).update!(bio: params[:user][:bio])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/buttons/_add_remove_friend.html.haml
%div{data:{controller: "friendship-button"}}
  %div{class: "#{"hidden" unless current_user.friends_with?(user)}", data: {friendship_button_target: "remove"}}
    = link_to "Remove friend", friendship_path(id: current_user.friendship_with(user) || "e"), method: :delete,
    data:{action: "click->friendship-button#showAdd"}
  %div{class: "#{"hidden" unless current_user.request_recipients.include?(user.id)}", data: {friendship_button_target: "cancel"}}
    = link_to "Cancel friend request", friend_request_path(current_user.request_to(user) || "e"), method: :delete,
      class: "px-3 py-1 text-gray-500 bg-gray-200 rounded shadow",
      data:{action: "click->friendship-button#showAdd"}
  %div{class: "#{"hidden" unless current_user.request_senders.include?(user.id)}", data: {friendship_button_target: "respond"}}
    .text-md.flex-grow.text-center
      wants to be friends
    .inline-flex.mx-auto
      = link_to "Accept", accept_friend_request_path(id: current_user.request_from(user) || "e"), method: :post,
                data: {action: "click->friendship-button#showAccepted"},
                class: "bg-blue-400 text-white px-2 rounded hover:bg-blue-500 mx-3"
      = link_to "Decline", friend_request_path(id: current_user.request_from(user) || "e"), method: :delete,
                data: {action: "click->friendship-button#showAdd"},
                class: "bg-gray-300 text-white px-2 rounded hover:bg-gray-400"
  %div{class: "#{"hidden" if current_user.friends_with?(user) || current_user.request_with(user)}", data:{friendship_button_target: "add"}}
    = link_to "Add friend", friend_requests_path(id: user), method: :post,
    class: "bg-blue-400 px-3 py-2 text-white rounded shadow",
    data:{action: "click->friendship-button#showSent"}
  .hidden.text-gray-600{data:{friendship_button_target: "sent"}}
    Request sent
  .hidden.text-gray-600{data:{friendship_button_target: "accepted"}}
    You are now friends

app/views/users/buttons/_bell.html.haml
.flex.cursor-pointer{data: {controller: "notifications", action: "click->notifications#toggle"}}
  = heroicon "bell",
  options: {class: "h-7 p-1 mr-3 text-white #{"fill-current" if enable} pointer-events-none"},
  variant: "outline"
  - if enable
    .text-yellow-400.absolute.ml-5.text-md
      ●