config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :update, :index]
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:destroy]
  resources :friend_requests, only: [:create, :destroy] do
    post "/accept", to: "friend_requests#accept", on: :member
    post "/generate", to: "friend_requests#generate", on: :collection
  end
  root 'posts#index'
  patch "/update_avatar/:id", to: "users#update_avatar", as: "update_avatar"
end

app/models/post.rb
include ActionView::Helpers::DateHelper


class Post < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: 'user_id'
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  scope :order_desc, ->{ all.order(created_at: :desc) }

  validates :body, presence: true, unless: ->{image.present?}
  validates :image, blob: { content_type: :image }

  after_create_commit {broadcast_prepend_to "posts", target: "posts"}
  after_destroy_commit {broadcast_remove_to "posts", target: self}

  def time_ago
    time_ago_in_words(created_at) + " ago"
  end
  
  def comments_and_replies
    out = []
    comments.each do |c|
      out << c
      c.all_replies.each {|r| out << r}
    end
    out.flatten
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @posts = Post.all
    if current_user.posts.build(body: post_params[:body], image: post_params[:image]).save
    end
  end

  def index
    @posts = Post.where(user_id: [*current_user.friends.pluck(:id), current_user.id]).order_desc
    @strangers = current_user.strangers.sample(5)
    post_likes = Post.joins(:likes).where("likes.created_at BETWEEN ? AND ?", 24.hours.ago, Time.now).group("likes.post_id").count
    @trending = post_likes.sort_by{|_k,v| v}.reverse.map(&:first).first(5).map {|id| Post.find(id)}

  end

  def destroy
    post = Post.find(params[:id])
    post.destroy!
    if request.referer[-6..-1] != ":3000/"
      redirect_to root_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @likers = @post.likers
  end

  private

  def post_params
    params.require(:post).permit([:body, :image])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_interactions.html.haml
%div
  = turbo_stream_from "likers"
  = turbo_stream_from "comments"
  = render "posts/likers", post: post
  = render "posts/buttons/like", post: post
  .text-gray-600.text-sm.text-center.border-b.mb-2
    Comments
  .max-h-52.overflow-y-auto
    = render "comments/for_commentable", commentable: post
  = render "comments/form", commentable: post

app/views/posts/_liker.html.haml
= link_to user, class: "pointer-hover inline-flex gap-2", id: dom_id(user) do
  = image_tag url_for(user.avatar_thumbnail("20")), class: "rounded"
  = user.first_name

app/views/posts/_likers.html.haml
.inline-flex.text-sm.text-gray-500{id: "likers#{post.id}"}
  - if post.likers.any?
    - latest_liker = post.likers.order(created_at: :desc).last
    = link_to latest_liker.first_name, latest_liker, class: "hover:underline mr-1"
    - if post.likers.many?
      .mr-1
        = link_to post_path(post) do
          .hover:underline
            and #{post.likers.count - 1}
            #{"other#{"s" if post.likers.count > 2}"}
    likes this

app/views/posts/_new.html.haml
= form_with scope: :post, url: posts_path, class: "mt-5 grid", data: {controller: "input", action: "turbo:submit-end->input#clear"} do |f|
  .inline-flex
    = f.text_area :body, placeholder: "Write something...", class: "w-full p-3 h-16 border-2 border-gray-200 rounded-md", data: {input_target: "input"}
    = f.file_field :image, hidden: true, data: {input_target: "file", action: "change->input#showFilename"}, accept: "image/png, image/gif, image/jpeg"
    = f.label :image, class: "self-center ml-2 cursor-pointer" do
      %i #{heroicon "photograph", options:{class: "h-7 text-blue-400 hover:text-blue-500"}}
  #file.hidden.mx-auto
    .bg-blue-200.rounded.text-center.text-gray-600.text-sm.w-max.mx-auto.px-2.mt-2.inline-flex.gap-2.items-center
      #file-name
      .cursor-pointer{data:{action:"click->input#replaceFileInput"}}
        = heroicon "x", options:{class: "h-4 text-gray-600 hover:text-red-400"}
  = f.submit "Post", class: "bg-blue-400 hover:bg-blue-500 cursor-pointer w-1/3 rounded mt-2 mx-auto text-white text-3xl font-medium", id: "submit", data: {disable_with: false}

app/views/posts/_post.html.haml
.grid.grid-rows-auto.border.rounded.p-3.shadow.gap-3.bg-white.hover{id: dom_id(post)}
  .inline-flex.items-center
    = link_to (controller_name == "users" ? "#" : user_path(post.author)),
      class: "inline-flex items-center gap-3 border-b w-max" do
      = image_tag url_for(post.author.avatar_thumbnail), class: "rounded"
      .text-gray-700
        #{post.author.full_name}
    .flex-grow.ml-3.text-sm.text-gray-500
      = post.time_ago
    = link_to post_path(post), method: :delete, data: {controller: "reveal-for", "reveal-for-id-value": post.author.id} do
      = heroicon "trash", options: {class: "h-5 text-gray-600 hover:text-red-600"}
    = link_to post do
      = heroicon "external-link", options: {class: "h-5 text-gray-500 hover:text-gray-700"}
  .text-lg.text-gray-700.break-all.mx-4
    = post.body
    - if post.image.attached?
      = image_tag url_for(post.image), class: "rounded-md mt-3"
  = render "posts/interactions", post: post

app/views/posts/_posts.html.haml
#posts.grid.grid-rows-auto.gap-4.mt-10
  - posts.each do |post|
    = futurize "posts/post", post: post, extends: :div do
      .text-center.py-4
        Loading...

app/views/posts/_trending.html.haml
.grid.grid-rows-auto.px-3.py-2.rounded.mt-48.border.shadow.bg-white.mx-auto{class: "w-2/3"}
  .text-4xl.font-medium.italic.text-blue-500.text-center.border-b.border-blue-200
    Trending
  .grid.grid-rows-auto.mt-3.gap-2
    - posts.each do |post|
      .p-2.rounded.shadow
        .inline-flex.w-full
          = link_to user_path(post.author), class: "inline-flex items-center gap-3 border-b w-max hover:underline" do
            = image_tag url_for(post.author.avatar_thumbnail("24")), class: "rounded"
            .text-gray-700
              #{post.author.full_name}
          .flex-grow
          = link_to post do
            = heroicon "external-link", options: {class: "h-5 text-gray-500 hover:text-gray-700"}
        .text-md.text-gray-700.break-all.mx-4.my-2.max-h-36.overflow-hidden
          = post.body
        .inline-flex.gap-2.text-sm
          .italic.text-gray-600
            #{post.likes.count} likes
          .italic.text-gray-600
            #{post.comments_and_replies.count} comments

app/views/posts/index.html.haml
= turbo_stream_from "posts"

.grid.grid-cols-3.mb-5
  %div#trending
    = render "posts/trending", posts: @trending
  %div
    = render 'new'
    = render "posts", posts: @posts.order_desc
  %div#people
    = render "users/strangers", strangers: @strangers

app/views/posts/show.html.haml
.grid.grid-rows-auto.border.rounded.p-3.shadow.gap-3.bg-white.mx-auto.mt-48{class: "w-1/2"}
  .inline-flex.items-center
    = link_to (controller_name == "users" ? "#" : user_path(@post.author)),
      class: "inline-flex items-center gap-3 border-b w-max" do
      = image_tag url_for(@post.author.avatar_thumbnail), class: "rounded"
      .text-gray-700
        #{@post.author.full_name}
    %div.flex-grow
    = link_to post_path(@post), method: :delete, data: {controller: "reveal-for", "reveal-for-id-value": @post.author.id} do
      = heroicon "trash", options: {class: "h-5 hover:text-red-600"}
  .text-lg.text-gray-700.break-all.border-b
    = @post.body
  = turbo_stream_from "comments"
  = turbo_stream_from "likers_full"
  = render "posts/buttons/like", post: @post
  .text-gray-600.italic
    #{@post.likes.count} likers:
  .max-h-36.overflow-y-auto
    .grid.grid-cols-5.gap-2{id: "likers#{@post.id}"}
      - @post.likers.each do |liker|
        = futurize "posts/liker", user: liker, extends: :div do
          loading...
  = render "comments/form", commentable: @post
  = render "comments/for_commentable", commentable: @post